POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "namleadmin@hotmail.com",
  "password": "namle123"
}


###
GET http://localhost:8080/api/v1/auth/get-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJuYW1sZWFkbWluQGhvdG1haWwuY29tIiwiaWF0IjoxNzU3OTkzMjA4LCJleHAiOjE3NTgwNzk2MDh9.BvkE7OiDiKymOjzRffS6hyvtbgLrh82X1PalMgXCNVs