POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "product_name": "Laptop Gaming Ascer ",
  "price": 2500000000000000,
  "discount": 10,
  "description": "Laptop gaming cấu hình mạnh, card rời RTX 3060",
  "stock": 15,
  "slug": "laptop-gaming-acer-nitro-56",
  "category":1,
  "brand": 1
}


### GET ALL
//get all products
GET http://localhost:8080/api/v1/products


###
GET http://localhost:8080/api/v1/products/2

###
PUT http://localhost:8080/api/v1/products/2
Content-Type: application/json

{
  "stock": 10
}


### DELETE
DELETE http://localhost:8080/api/v1/products/689ecd14a918d4495b28049d