POST http://localhost:8080/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJuYW1sZWFkbWluQGhvdG1haWwuY29tIiwiaWF0IjoxNzU4MTc1MjYzLCJleHAiOjE3NTgyNjE2NjN9.zQC3gSYIx15Fd7Mas5BZUp5DaheYRceSxHsEHvdnLls

{
  "product_name": "Sony WH-7000XM5",
  "thumbnail": "https://example.com/images/sony-wh1000xm5-thumb.jpg",
  "price": 7990000,
  "discount": 200000,
  "stock": 50,
  "sku": "SONY-WH1000XM5-2025",
  "barcode": "8938505974154",
  "status": "Available",
  "description": "Tai nghe chống ồn cao cấp, pin 30 giờ, kết nối Bluetooth 5.2",
  "isFeatured": false,
  "isActive": true,
  "category": 2,
  "brand": 3,
  "images": [
    { "url": "https://example.com/images/sony-wh1000xm5-1.jpg" },
    { "url": "https://example.com/images/sony-wh1000xm5-2.jpg" }
  ]
}




### GET ALL
//get all products
GET http://localhost:8080/api/v1/products


###
GET http://localhost:8080/api/v1/products/2

###
PUT http://localhost:8080/api/v1/products/2
Content-Type: application/json

{
  "stock": 10
}


### DELETE
DELETE http://localhost:8080/api/v1/products/689ecd14a918d4495b28049d


### Get
GET http://localhost:8080/api/v1/products?page=1&limit=10&search=Samsung 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJuYW1sZWFkbWluQGhvdG1haWwuY29tIiwiaWF0IjoxNzU4MTc1MjYzLCJleHAiOjE3NTgyNjE2NjN9.zQC3gSYIx15Fd7Mas5BZUp5DaheYRceSxHsEHvdnLls
